name: skawa_components
version: 0.0.11

dependencies:
  angular: 4.0.0
  angular_components: 0.8.0
  angular_router: 1.0.2
  angular_forms: 1.0.0
  quiver: 0.25.0
dev_dependencies:
  sass_builder: 1.0.1
  test: 0.12.26
  angular_test: 1.0.1
  browser:
  angular_utility:
    git: https://github.com/skawa-universe/angular_utility.git
  html_unescape: ^0.1.5
dependency_overrides:
  sass:
    git:
      url: https://github.com/sass/dart-sass
      ref: e958477
transformers:
- angular
- test/pub_serve:
   $include: test/**_test.dart